/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Replace the password, revoke all sessions, then clear browser state.
         */
        post: operations["change_password_api_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Rate-limit credentials, commit one session, then deliver browser tokens.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke one browser family and clear its cookies after commit.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current User
         * @description Return only identity and memberships revalidated for this request.
         */
        get: operations["current_user_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Session
         * @description Rotate browser session credentials and return one new Access Token.
         */
        post: operations["refresh_session_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register User
         * @description Register an account and its initial owner workspace atomically.
         */
        post: operations["register_user_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces */
        get: operations["list_workspaces_api_v1_workspaces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspace Members */
        get: operations["list_workspace_members_api_v1_workspaces__workspace_id__members_get"];
        put?: never;
        /** Add Workspace Member */
        post: operations["add_workspace_member_api_v1_workspaces__workspace_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Workspace Member */
        delete: operations["remove_workspace_member_api_v1_workspaces__workspace_id__members__user_id__delete"];
        options?: never;
        head?: never;
        /** Change Workspace Member Role */
        patch: operations["change_workspace_member_role_api_v1_workspaces__workspace_id__members__user_id__patch"];
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AccountStatus: "active" | "disabled" | "deleting" | "deleted";
        /** AddWorkspaceMemberRequest */
        AddWorkspaceMemberRequest: {
            role: components["schemas"]["WorkspaceRoleName"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * AuthenticatedUser
         * @description Safe user identity returned by registration and login.
         */
        AuthenticatedUser: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * ChangePasswordRequest
         * @description Current proof and policy-compliant replacement accepted from one user.
         */
        ChangePasswordRequest: {
            /**
             * Current Password
             * Format: password
             */
            current_password: string;
            /**
             * New Password
             * Format: password
             */
            new_password: string;
        };
        /** ChangeWorkspaceMemberRoleRequest */
        ChangeWorkspaceMemberRoleRequest: {
            role: components["schemas"]["WorkspaceRoleName"];
        };
        /**
         * CurrentUserResponse
         * @description Current server-verified account and its live Workspace memberships.
         */
        CurrentUserResponse: {
            user: components["schemas"]["AuthenticatedUser"];
            /** Workspaces */
            workspaces: components["schemas"]["CurrentWorkspace"][];
        };
        /**
         * CurrentWorkspace
         * @description One live Workspace membership returned by the current-user endpoint.
         */
        CurrentWorkspace: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "admin" | "member" | "viewer";
        };
        /**
         * DependencyStatus
         * @description Public status of one required dependency.
         * @enum {string}
         */
        DependencyStatus: "ok" | "failed";
        /**
         * LivenessResponse
         * @description Stable public contract for the liveness endpoint.
         */
        LivenessResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * LoginRequest
         * @description Untrusted credentials accepted without applying the new-password policy.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /**
         * LoginResponse
         * @description Short-lived Access Token and safe identity returned after login.
         */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Token Type
             * @default Bearer
             * @constant
             */
            token_type: "Bearer";
            user: components["schemas"]["AuthenticatedUser"];
        };
        /**
         * ReadinessChecks
         * @description Public status of each required dependency.
         */
        ReadinessChecks: {
            postgres: components["schemas"]["DependencyStatus"];
            redis: components["schemas"]["DependencyStatus"];
        };
        /**
         * ReadinessResponse
         * @description Stable public contract for the readiness endpoint.
         */
        ReadinessResponse: {
            checks: components["schemas"]["ReadinessChecks"];
            status: components["schemas"]["ReadinessStatus"];
        };
        /**
         * ReadinessStatus
         * @description Public readiness state of the API.
         * @enum {string}
         */
        ReadinessStatus: "ready" | "not_ready";
        /**
         * RefreshResponse
         * @description New short-lived Access Token returned after safe session rotation.
         */
        RefreshResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Token Type
             * @default Bearer
             * @constant
             */
            token_type: "Bearer";
        };
        /**
         * RegisterRequest
         * @description Untrusted JSON accepted by the public registration endpoint.
         */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /**
         * RegisteredWorkspace
         * @description Safe initial-workspace fields returned after registration.
         */
        RegisteredWorkspace: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @constant
             */
            role: "owner";
        };
        /**
         * RegistrationResponse
         * @description Public representation of a completed registration.
         */
        RegistrationResponse: {
            user: components["schemas"]["AuthenticatedUser"];
            workspace: components["schemas"]["RegisteredWorkspace"];
        };
        /** WorkspaceCollectionResponse */
        WorkspaceCollectionResponse: {
            /** Workspaces */
            workspaces: components["schemas"]["WorkspaceResponse"][];
        };
        /** WorkspaceMemberCollectionResponse */
        WorkspaceMemberCollectionResponse: {
            /** Members */
            members: components["schemas"]["WorkspaceMemberResponse"][];
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** WorkspaceMemberResponse */
        WorkspaceMemberResponse: {
            account_status: components["schemas"]["AccountStatus"];
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Membership Id
             * Format: uuid
             */
            membership_id: string;
            role: components["schemas"]["WorkspaceRoleName"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** WorkspaceMembershipResponse */
        WorkspaceMembershipResponse: {
            /**
             * Membership Id
             * Format: uuid
             */
            membership_id: string;
            role: components["schemas"]["WorkspaceRoleName"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** WorkspaceResponse */
        WorkspaceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            role: components["schemas"]["WorkspaceRoleName"];
        };
        /** @enum {string} */
        WorkspaceRoleName: "owner" | "admin" | "member" | "viewer";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    change_password_api_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Current password is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Invalid authenticated session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Password change request rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Password changed concurrently */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Password change rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Password change temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Login rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Login temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid logout session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Logout temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
        };
    };
    current_user_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            /** @description Invalid authenticated session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Identity temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
        };
    };
    refresh_session_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Invalid refresh session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Refresh temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
        };
    };
    register_user_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationResponse"];
                };
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Registration temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
        };
    };
    list_workspaces_api_v1_workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceCollectionResponse"];
                };
            };
            /** @description Invalid authenticated session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Workspace service temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
        };
    };
    list_workspace_members_api_v1_workspaces__workspace_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMemberCollectionResponse"];
                };
            };
            /** @description Invalid authenticated session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Workspace access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Workspace service temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
        };
    };
    add_workspace_member_api_v1_workspaces__workspace_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddWorkspaceMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMembershipResponse"];
                };
            };
            /** @description Invalid authenticated session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Workspace access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Workspace member not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Workspace membership conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Workspace service temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
        };
    };
    remove_workspace_member_api_v1_workspaces__workspace_id__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid authenticated session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Workspace access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Workspace member not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Workspace membership conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Workspace service temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
        };
    };
    change_workspace_member_role_api_v1_workspaces__workspace_id__members__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeWorkspaceMemberRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMembershipResponse"];
                };
            };
            /** @description Invalid authenticated session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Workspace access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Workspace member not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Workspace membership conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Workspace service temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Code */
                        code: string;
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Trace Id */
                        trace_id: string;
                        /** Type */
                        type: string;
                    };
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
