"""PostgreSQL metadata, engine construction, and connectivity checks."""

from datetime import datetime
from uuid import UUID, uuid4

from sqlalchemy import URL, DateTime, MetaData, Uuid, func, text
from sqlalchemy.exc import DBAPIError, SQLAlchemyError
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from industry_platform.core.config import Settings

NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

type AsyncSessionFactory = async_sessionmaker[AsyncSession]


def safe_sqlstate(error: SQLAlchemyError) -> str | None:
    """Return only PostgreSQL's non-sensitive five-character error class."""

    if not isinstance(error, DBAPIError):
        return None

    sqlstate = getattr(error.orig, "sqlstate", None)
    return sqlstate if isinstance(sqlstate, str) and len(sqlstate) == 5 else None


class Base(DeclarativeBase):
    """Base class shared by every SQLAlchemy ORM model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """Give a model a UUID primary key generated by Python or PostgreSQL."""

    id: Mapped[UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid4,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """Give a model timezone-aware creation and update timestamps."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


def build_database_url(settings: Settings) -> URL:
    """Build one structured PostgreSQL URL from validated settings."""

    return URL.create(
        drivername="postgresql+psycopg",
        username=settings.postgres_user,
        password=settings.postgres_password.get_secret_value(),
        host=settings.postgres_host,
        port=settings.postgres_port,
        database=settings.postgres_db,
    )


def create_database_engine(settings: Settings) -> AsyncEngine:
    """Create the process-wide asynchronous PostgreSQL engine."""

    return create_async_engine(
        build_database_url(settings),
        pool_pre_ping=True,
    )


def create_database_session_factory(
    engine: AsyncEngine,
) -> AsyncSessionFactory:
    """Create request/task-scoped sessions from the process-wide engine."""

    return async_sessionmaker(
        bind=engine,
        autoflush=False,
        expire_on_commit=False,
    )


async def check_database_connection(engine: AsyncEngine) -> None:
    """Raise when PostgreSQL cannot execute a minimal query."""

    async with engine.connect() as connection:
        await connection.execute(text("SELECT 1"))
