"""create file objects and message attachments

Revision ID: 0ed29898ae52
Revises: ea2832a756ce
Create Date: 2026-08-14 19:18:55.025200

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic.
revision: str = "0ed29898ae52"
down_revision: str | Sequence[str] | None = "ea2832a756ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_objects",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("declared_media_type", sa.String(length=64), nullable=False),
        sa.Column(
            "detected_media_type",
            sa.Enum(
                "text/plain",
                "text/markdown",
                "image/png",
                "image/jpeg",
                "image/webp",
                name="attachment_media_type",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "kind",
            sa.Enum("text", "image", name="attachment_kind", native_enum=False, length=16),
            nullable=True,
        ),
        sa.Column("bucket", sa.String(length=63), nullable=False),
        sa.Column("staging_object_key", sa.String(length=512), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=True),
        sa.Column("expected_size", sa.BigInteger(), nullable=False),
        sa.Column("actual_size", sa.BigInteger(), nullable=True),
        sa.Column("safe_size", sa.BigInteger(), nullable=True),
        sa.Column("expected_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=True),
        sa.Column("safe_sha256", sa.String(length=64), nullable=True),
        sa.Column("source_etag", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "staging",
                "processing",
                "ready",
                "rejected",
                "failed",
                "deleting",
                "deleted",
                name="file_object_status",
                native_enum=False,
                length=16,
            ),
            server_default="staging",
            nullable=False,
        ),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("parser_version", sa.String(length=128), nullable=True),
        sa.Column("sanitizer_version", sa.String(length=128), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("upload_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processing_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attached_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delete_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'text' AND extracted_text IS NOT NULL "
            "AND width IS NULL AND height IS NULL) OR "
            "(kind = 'image' AND extracted_text IS NULL "
            "AND width IS NOT NULL AND height IS NOT NULL) OR kind IS NULL",
            name=op.f("ck_file_objects_kind_payload_consistent"),
        ),
        sa.CheckConstraint(
            "(status = 'deleted' AND deleted_at IS NOT NULL) OR status <> 'deleted'",
            name=op.f("ck_file_objects_deleted_state_consistent"),
        ),
        sa.CheckConstraint(
            "(status = 'ready' AND object_key IS NOT NULL "
            "AND detected_media_type IS NOT NULL AND kind IS NOT NULL "
            "AND actual_size IS NOT NULL AND safe_size IS NOT NULL "
            "AND source_sha256 IS NOT NULL AND safe_sha256 IS NOT NULL "
            "AND parser_version IS NOT NULL AND sanitizer_version IS NOT NULL "
            "AND ready_at IS NOT NULL AND error_code IS NULL) OR status <> 'ready'",
            name=op.f("ck_file_objects_ready_state_consistent"),
        ),
        sa.CheckConstraint(
            "(status = 'staging' AND actual_size IS NULL AND object_key IS NULL "
            "AND ready_at IS NULL AND error_code IS NULL) OR status <> 'staging'",
            name=op.f("ck_file_objects_staging_state_consistent"),
        ),
        sa.CheckConstraint(
            "(status IN ('rejected', 'failed') AND error_code IS NOT NULL) "
            "OR status NOT IN ('rejected', 'failed')",
            name=op.f("ck_file_objects_failure_has_error_code"),
        ),
        sa.CheckConstraint(
            "status IN ('staging', 'processing', 'ready', 'rejected', "
            "'failed', 'deleting', 'deleted')",
            name=op.f("ck_file_objects_status"),
        ),
        sa.CheckConstraint(
            "actual_size IS NULL OR actual_size > 0",
            name=op.f("ck_file_objects_actual_size_positive"),
        ),
        sa.CheckConstraint(
            "expected_size > 0", name=op.f("ck_file_objects_expected_size_positive")
        ),
        sa.CheckConstraint("revision >= 0", name=op.f("ck_file_objects_revision_nonnegative")),
        sa.CheckConstraint(
            "safe_size IS NULL OR safe_size > 0", name=op.f("ck_file_objects_safe_size_positive")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_file_objects_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_file_objects_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_objects")),
        sa.UniqueConstraint(
            "bucket", "staging_object_key", name=op.f("uq_file_objects_bucket_staging_object_key")
        ),
        sa.UniqueConstraint("id", "workspace_id", name=op.f("uq_file_objects_id_workspace_id")),
    )
    op.create_index(
        op.f("ix_file_objects_upload_expires_at"),
        "file_objects",
        ["upload_expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'staging'"),
    )
    op.create_index(
        op.f("ix_file_objects_workspace_id_status_updated_at_id"),
        "file_objects",
        ["workspace_id", "status", "updated_at", "id"],
        unique=False,
    )
    op.create_index(
        "uq_file_objects_final_object_key",
        "file_objects",
        ["bucket", "object_key"],
        unique=True,
        postgresql_where=sa.text("object_key IS NOT NULL"),
    )
    op.create_unique_constraint(
        op.f("uq_conversation_messages_id_workspace_id"),
        "conversation_messages",
        ["id", "workspace_id"],
    )
    op.create_table(
        "message_attachments",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "ordinal >= 0 AND ordinal < 4", name=op.f("ck_message_attachments_ordinal_bounded")
        ),
        sa.ForeignKeyConstraint(
            ["file_id", "workspace_id"],
            ["file_objects.id", "file_objects.workspace_id"],
            name=op.f("fk_message_attachments_file_id_workspace_id_file_objects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["message_id", "workspace_id"],
            ["conversation_messages.id", "conversation_messages.workspace_id"],
            name=op.f("fk_message_attachments_message_id_workspace_id_conversation_messages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("message_id", "file_id", name=op.f("pk_message_attachments")),
        sa.UniqueConstraint("file_id", name=op.f("uq_message_attachments_file_id")),
        sa.UniqueConstraint(
            "message_id", "ordinal", name=op.f("uq_message_attachments_message_id_ordinal")
        ),
    )
    op.create_index(
        op.f("ix_message_attachments_workspace_id_message_id_ordinal"),
        "message_attachments",
        ["workspace_id", "message_id", "ordinal"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_message_attachments_workspace_id_message_id_ordinal"),
        table_name="message_attachments",
    )
    op.drop_table("message_attachments")
    op.drop_constraint(
        op.f("uq_conversation_messages_id_workspace_id"),
        "conversation_messages",
        type_="unique",
    )
    op.drop_index(
        "uq_file_objects_final_object_key",
        table_name="file_objects",
        postgresql_where=sa.text("object_key IS NOT NULL"),
    )
    op.drop_index(
        op.f("ix_file_objects_workspace_id_status_updated_at_id"), table_name="file_objects"
    )
    op.drop_index(
        op.f("ix_file_objects_upload_expires_at"),
        table_name="file_objects",
        postgresql_where=sa.text("status = 'staging'"),
    )
    op.drop_table("file_objects")
    # ### end Alembic commands ###
