"""create reliable job outbox and schedule schema

Revision ID: 198d18b12698
Revises: 92864e62ffff
Create Date: 2026-08-11 23:36:42.057078

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision: str = "198d18b12698"
down_revision: str | Sequence[str] | None = "92864e62ffff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("system_scope_key", sa.String(length=128), nullable=True),
        sa.Column("task_name", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("queue_name", sa.String(length=64), server_default="default", nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "payload_schema_version", sa.SmallInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "dispatched",
                "running",
                "retry_wait",
                "succeeded",
                "failed",
                "cancelled",
                "dead_letter",
                name="job_status",
                native_enum=False,
                length=16,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("idempotency_key_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("request_fingerprint", sa.LargeBinary(length=32), nullable=True),
        sa.Column("priority", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.SmallInteger(), server_default=sa.text("3"), nullable=False),
        sa.Column("generation", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("dispatch_generation", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "dispatch_attempt", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("fencing_token", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("stage_name", sa.String(length=100), server_default="pending", nullable=False),
        sa.Column("stage_sequence", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "soft_time_limit_seconds", sa.Integer(), server_default=sa.text("1500"), nullable=False
        ),
        sa.Column(
            "hard_time_limit_seconds", sa.Integer(), server_default=sa.text("1800"), nullable=False
        ),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terminal_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'running' AND lease_owner IS NOT NULL "
            "AND lease_token IS NOT NULL AND lease_expires_at IS NOT NULL "
            "AND heartbeat_at IS NOT NULL AND fencing_token > 0 "
            "AND lease_expires_at > heartbeat_at) OR "
            "(status <> 'running' AND lease_owner IS NULL "
            "AND lease_token IS NULL AND lease_expires_at IS NULL "
            "AND heartbeat_at IS NULL)",
            name=op.f("ck_jobs_lease_state_consistent"),
        ),
        sa.CheckConstraint(
            "(status IN ('succeeded', 'failed', 'cancelled', 'dead_letter') "
            "AND terminal_at IS NOT NULL) OR "
            "(status NOT IN ('succeeded', 'failed', 'cancelled', 'dead_letter') "
            "AND terminal_at IS NULL)",
            name=op.f("ck_jobs_terminal_state_consistent"),
        ),
        sa.CheckConstraint(
            "result IS NULL OR status = 'succeeded'", name=op.f("ck_jobs_result_only_on_success")
        ),
        sa.CheckConstraint(
            "status <> 'dispatched' OR (dispatched_at IS NOT NULL AND started_at IS NULL)",
            name=op.f("ck_jobs_dispatched_not_started"),
        ),
        sa.CheckConstraint(
            "status <> 'running' OR started_at IS NOT NULL",
            name=op.f("ck_jobs_running_has_started"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'dispatched', 'running', 'retry_wait', "
            "'succeeded', 'failed', 'cancelled', 'dead_letter')",
            name=op.f("ck_jobs_status"),
        ),
        sa.CheckConstraint(
            "(dispatch_generation = 0 AND dispatch_attempt = 0 "
            "AND dispatched_at IS NULL AND started_at IS NULL) OR "
            "(dispatch_generation > 0 AND "
            "((dispatch_attempt = 0 AND dispatched_at IS NULL "
            "AND started_at IS NULL) OR "
            "(dispatch_attempt > 0 AND dispatched_at IS NOT NULL)))",
            name=op.f("ck_jobs_dispatch_state_consistent"),
        ),
        sa.CheckConstraint(
            "(idempotency_key_hash IS NULL AND request_fingerprint IS NULL) OR "
            "(idempotency_key_hash IS NOT NULL "
            "AND request_fingerprint IS NOT NULL)",
            name=op.f("ck_jobs_idempotency_fields_paired"),
        ),
        sa.CheckConstraint(
            "(workspace_id IS NOT NULL AND system_scope_key IS NULL) OR "
            "(workspace_id IS NULL AND system_scope_key IS NOT NULL "
            "AND length(btrim(system_scope_key)) > 0)",
            name=op.f("ck_jobs_execution_scope"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0 AND max_attempts >= 1 AND attempt_count <= max_attempts",
            name=op.f("ck_jobs_attempt_bounds"),
        ),
        sa.CheckConstraint(
            "dispatch_attempt >= 0", name=op.f("ck_jobs_dispatch_attempt_nonnegative")
        ),
        sa.CheckConstraint(
            "dispatch_generation >= 0", name=op.f("ck_jobs_dispatch_generation_nonnegative")
        ),
        sa.CheckConstraint("fencing_token >= 0", name=op.f("ck_jobs_fencing_token_nonnegative")),
        sa.CheckConstraint("generation >= 0", name=op.f("ck_jobs_generation_nonnegative")),
        sa.CheckConstraint(
            "idempotency_key_hash IS NULL OR octet_length(idempotency_key_hash) = 32",
            name=op.f("ck_jobs_idempotency_key_hash_length"),
        ),
        sa.CheckConstraint(
            "lease_owner IS NULL OR length(btrim(lease_owner)) > 0",
            name=op.f("ck_jobs_lease_owner_not_blank"),
        ),
        sa.CheckConstraint(
            "length(btrim(queue_name)) > 0", name=op.f("ck_jobs_queue_name_not_blank")
        ),
        sa.CheckConstraint(
            "length(btrim(stage_name)) > 0", name=op.f("ck_jobs_stage_name_not_blank")
        ),
        sa.CheckConstraint(
            "length(btrim(task_name)) > 0", name=op.f("ck_jobs_task_name_not_blank")
        ),
        sa.CheckConstraint("length(btrim(trace_id)) > 0", name=op.f("ck_jobs_trace_id_not_blank")),
        sa.CheckConstraint(
            "payload_schema_version > 0", name=op.f("ck_jobs_payload_schema_version_positive")
        ),
        sa.CheckConstraint("priority BETWEEN -100 AND 100", name=op.f("ck_jobs_priority_bounds")),
        sa.CheckConstraint(
            "request_fingerprint IS NULL OR octet_length(request_fingerprint) = 32",
            name=op.f("ck_jobs_request_fingerprint_length"),
        ),
        sa.CheckConstraint(
            "soft_time_limit_seconds >= 1 "
            "AND hard_time_limit_seconds > soft_time_limit_seconds "
            "AND hard_time_limit_seconds <= 1800",
            name=op.f("ck_jobs_time_limit_bounds"),
        ),
        sa.CheckConstraint("stage_sequence >= 0", name=op.f("ck_jobs_stage_sequence_nonnegative")),
        sa.CheckConstraint(
            "started_at IS NULL OR dispatched_at <= started_at",
            name=op.f("ck_jobs_dispatch_start_order"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_jobs_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(
        "ix_jobs_expired_leases",
        "jobs",
        ["lease_expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_index(
        op.f("ix_jobs_status_available_at_priority_created_at"),
        "jobs",
        ["status", "available_at", "priority", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_jobs_system_idempotency",
        "jobs",
        ["system_scope_key", "task_name", "idempotency_key_hash"],
        unique=True,
        postgresql_where=sa.text(
            "system_scope_key IS NOT NULL AND idempotency_key_hash IS NOT NULL"
        ),
    )
    op.create_index(
        "uq_jobs_workspace_idempotency",
        "jobs",
        ["workspace_id", "task_name", "idempotency_key_hash"],
        unique=True,
        postgresql_where=sa.text("workspace_id IS NOT NULL AND idempotency_key_hash IS NOT NULL"),
    )
    op.create_table(
        "schedules",
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("system_scope_key", sa.String(length=128), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("task_name", sa.String(length=128), nullable=False),
        sa.Column("queue_name", sa.String(length=64), server_default="default", nullable=False),
        sa.Column("max_attempts", sa.SmallInteger(), server_default=sa.text("3"), nullable=False),
        sa.Column("priority", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "soft_time_limit_seconds", sa.Integer(), server_default=sa.text("1500"), nullable=False
        ),
        sa.Column(
            "hard_time_limit_seconds", sa.Integer(), server_default=sa.text("1800"), nullable=False
        ),
        sa.Column("cron_expression", sa.String(length=120), nullable=False),
        sa.Column("timezone_name", sa.String(length=100), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "misfire_policy",
            sa.Enum(
                "catch_up_each",
                "coalesce_latest",
                "manual",
                name="schedule_misfire_policy",
                native_enum=False,
                length=16,
            ),
            server_default="catch_up_each",
            nullable=False,
        ),
        sa.Column(
            "catch_up_window_seconds", sa.Integer(), server_default=sa.text("86400"), nullable=False
        ),
        sa.Column("max_catch_up", sa.SmallInteger(), server_default=sa.text("100"), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("next_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_fired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("misfire_blocked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("misfire_error_code", sa.String(length=100), nullable=True),
        sa.Column("missed_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("missed_through", sa.DateTime(timezone=True), nullable=True),
        sa.Column("missed_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "missed_count_is_lower_bound",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "misfire_policy IN ('catch_up_each', 'coalesce_latest', 'manual')",
            name=op.f("ck_schedules_misfire_policy"),
        ),
        sa.CheckConstraint(
            "(misfire_blocked_at IS NULL AND misfire_error_code IS NULL "
            "AND missed_from IS NULL AND missed_through IS NULL "
            "AND missed_count = 0 AND NOT missed_count_is_lower_bound) OR "
            "(misfire_blocked_at IS NOT NULL AND NOT enabled "
            "AND misfire_error_code IS NOT NULL AND next_due_at IS NOT NULL "
            "AND missed_from IS NOT NULL "
            "AND missed_through IS NOT NULL AND missed_count > 0 "
            "AND missed_from <= missed_through)",
            name=op.f("ck_schedules_misfire_block_state_consistent"),
        ),
        sa.CheckConstraint(
            "(workspace_id IS NOT NULL AND system_scope_key IS NULL) OR "
            "(workspace_id IS NULL AND system_scope_key IS NOT NULL "
            "AND length(btrim(system_scope_key)) > 0)",
            name=op.f("ck_schedules_execution_scope"),
        ),
        sa.CheckConstraint(
            "NOT enabled OR next_due_at IS NOT NULL",
            name=op.f("ck_schedules_enabled_has_next_fire"),
        ),
        sa.CheckConstraint(
            "catch_up_window_seconds >= 1 AND catch_up_window_seconds <= 604800",
            name=op.f("ck_schedules_catch_up_window_bounds"),
        ),
        sa.CheckConstraint(
            "last_fired_at IS NULL OR next_due_at IS NULL OR last_fired_at < next_due_at",
            name=op.f("ck_schedules_fire_order"),
        ),
        sa.CheckConstraint(
            "length(btrim(cron_expression)) > 0", name=op.f("ck_schedules_cron_not_blank")
        ),
        sa.CheckConstraint("length(btrim(name)) > 0", name=op.f("ck_schedules_name_not_blank")),
        sa.CheckConstraint(
            "length(btrim(queue_name)) > 0", name=op.f("ck_schedules_queue_name_not_blank")
        ),
        sa.CheckConstraint(
            "length(btrim(task_name)) > 0", name=op.f("ck_schedules_task_name_not_blank")
        ),
        sa.CheckConstraint(
            "length(btrim(timezone_name)) > 0", name=op.f("ck_schedules_timezone_not_blank")
        ),
        sa.CheckConstraint(
            "max_catch_up >= 1 AND max_catch_up <= 1000",
            name=op.f("ck_schedules_max_catch_up_bounds"),
        ),
        sa.CheckConstraint(
            "max_attempts >= 1 AND max_attempts <= 100",
            name=op.f("ck_schedules_attempt_bounds"),
        ),
        sa.CheckConstraint(
            "priority BETWEEN -100 AND 100",
            name=op.f("ck_schedules_priority_bounds"),
        ),
        sa.CheckConstraint(
            "soft_time_limit_seconds >= 1 "
            "AND hard_time_limit_seconds > soft_time_limit_seconds "
            "AND hard_time_limit_seconds <= 1800",
            name=op.f("ck_schedules_time_limit_bounds"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_schedules_version_positive")),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_schedules_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedules")),
    )
    op.create_index(
        "ix_schedules_due",
        "schedules",
        ["next_due_at", "id"],
        unique=False,
        postgresql_where=sa.text("enabled"),
    )
    op.create_index(
        "uq_schedules_system_name",
        "schedules",
        ["system_scope_key", "name"],
        unique=True,
        postgresql_where=sa.text("system_scope_key IS NOT NULL"),
    )
    op.create_index(
        "uq_schedules_workspace_name",
        "schedules",
        ["workspace_id", "name"],
        unique=True,
        postgresql_where=sa.text("workspace_id IS NOT NULL"),
    )
    op.create_table(
        "job_events",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "created",
                "dispatched",
                "started",
                "heartbeat",
                "retry_scheduled",
                "lease_expired",
                "succeeded",
                "failed",
                "cancelled",
                "dead_letter",
                name="job_event_type",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("dispatch_generation", sa.Integer(), nullable=False),
        sa.Column("fencing_token", sa.BigInteger(), nullable=False),
        sa.Column("event_sequence", sa.Integer(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('created', 'dispatched', 'started', 'heartbeat', "
            "'retry_scheduled', 'lease_expired', 'succeeded', 'failed', "
            "'cancelled', 'dead_letter')",
            name=op.f("ck_job_events_event_type"),
        ),
        sa.CheckConstraint(
            "dispatch_generation >= 0", name=op.f("ck_job_events_dispatch_generation_nonnegative")
        ),
        sa.CheckConstraint(
            "event_sequence >= 0", name=op.f("ck_job_events_event_sequence_nonnegative")
        ),
        sa.CheckConstraint(
            "fencing_token >= 0", name=op.f("ck_job_events_fencing_token_nonnegative")
        ),
        sa.CheckConstraint("generation >= 0", name=op.f("ck_job_events_generation_nonnegative")),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_events_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_events")),
        sa.UniqueConstraint(
            "job_id",
            "generation",
            "event_sequence",
            name=op.f("uq_job_events_job_id_generation_event_sequence"),
        ),
    )
    op.create_index(
        op.f("ix_job_events_job_id_occurred_at"),
        "job_events",
        ["job_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "uq_job_events_one_terminal_per_job",
        "job_events",
        ["job_id"],
        unique=True,
        postgresql_where=sa.text(
            "event_type IN ('succeeded', 'failed', 'cancelled', 'dead_letter')"
        ),
    )
    op.create_table(
        "outbox_events",
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("system_scope_key", sa.String(length=128), nullable=True),
        sa.Column("source_job_id", sa.Uuid(), nullable=True),
        sa.Column("job_dispatch_generation", sa.Integer(), nullable=True),
        sa.Column("topic", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("deduplication_key", sa.String(length=200), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "publishing",
                "published",
                "dead_letter",
                name="outbox_status",
                native_enum=False,
                length=16,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.SmallInteger(), server_default=sa.text("20"), nullable=False),
        sa.Column("claim_generation", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("claim_token", sa.Uuid(), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lock_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terminal_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'published' AND published_at IS NOT NULL) OR "
            "(status <> 'published' AND published_at IS NULL)",
            name=op.f("ck_outbox_events_published_state_consistent"),
        ),
        sa.CheckConstraint(
            "(status = 'publishing' AND locked_by IS NOT NULL "
            "AND claim_token IS NOT NULL AND locked_at IS NOT NULL "
            "AND lock_expires_at IS NOT NULL AND claim_generation > 0 "
            "AND lock_expires_at > locked_at) OR "
            "(status <> 'publishing' AND locked_by IS NULL "
            "AND claim_token IS NULL AND locked_at IS NULL "
            "AND lock_expires_at IS NULL)",
            name=op.f("ck_outbox_events_claim_state_consistent"),
        ),
        sa.CheckConstraint(
            "(status IN ('published', 'dead_letter') "
            "AND terminal_at IS NOT NULL) OR "
            "(status NOT IN ('published', 'dead_letter') "
            "AND terminal_at IS NULL)",
            name=op.f("ck_outbox_events_terminal_state_consistent"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'publishing', 'published', 'dead_letter')",
            name=op.f("ck_outbox_events_status"),
        ),
        sa.CheckConstraint(
            "(source_job_id IS NULL AND job_dispatch_generation IS NULL) OR "
            "(source_job_id IS NOT NULL AND job_dispatch_generation > 0)",
            name=op.f("ck_outbox_events_job_dispatch_generation_paired"),
        ),
        sa.CheckConstraint(
            "(workspace_id IS NOT NULL AND system_scope_key IS NULL) OR "
            "(workspace_id IS NULL AND system_scope_key IS NOT NULL "
            "AND length(btrim(system_scope_key)) > 0)",
            name=op.f("ck_outbox_events_execution_scope"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0 AND max_attempts >= 1 AND attempt_count <= max_attempts",
            name=op.f("ck_outbox_events_attempt_bounds"),
        ),
        sa.CheckConstraint(
            "claim_generation >= 0", name=op.f("ck_outbox_events_claim_generation_nonnegative")
        ),
        sa.CheckConstraint(
            "deduplication_key IS NULL OR length(btrim(deduplication_key)) > 0",
            name=op.f("ck_outbox_events_deduplication_key_not_blank"),
        ),
        sa.CheckConstraint(
            "length(btrim(event_type)) > 0", name=op.f("ck_outbox_events_event_type_not_blank")
        ),
        sa.CheckConstraint(
            "length(btrim(topic)) > 0", name=op.f("ck_outbox_events_topic_not_blank")
        ),
        sa.CheckConstraint(
            "locked_by IS NULL OR length(btrim(locked_by)) > 0",
            name=op.f("ck_outbox_events_locked_by_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["source_job_id"],
            ["jobs.id"],
            name=op.f("fk_outbox_events_source_job_id_jobs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_outbox_events_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
    )
    op.create_index(
        "ix_outbox_events_expired_claims",
        "outbox_events",
        ["lock_expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'publishing'"),
    )
    op.create_index(
        op.f("ix_outbox_events_status_next_attempt_at_created_at"),
        "outbox_events",
        ["status", "next_attempt_at", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_outbox_job_dispatch_generation",
        "outbox_events",
        ["source_job_id", "job_dispatch_generation"],
        unique=True,
        postgresql_where=sa.text("source_job_id IS NOT NULL"),
    )
    op.create_index(
        "uq_outbox_system_deduplication",
        "outbox_events",
        ["system_scope_key", "topic", "deduplication_key"],
        unique=True,
        postgresql_where=sa.text("system_scope_key IS NOT NULL AND deduplication_key IS NOT NULL"),
    )
    op.create_index(
        "uq_outbox_workspace_deduplication",
        "outbox_events",
        ["workspace_id", "topic", "deduplication_key"],
        unique=True,
        postgresql_where=sa.text("workspace_id IS NOT NULL AND deduplication_key IS NOT NULL"),
    )
    op.create_table(
        "schedule_occurrences",
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column(
            "trigger_kind",
            sa.Enum(
                "scheduled", "manual", name="schedule_trigger_kind", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trigger_id", sa.Uuid(), nullable=True),
        sa.Column("schedule_version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "materialized",
                "misfire_blocked",
                name="schedule_occurrence_status",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("coalesced_count", sa.Integer(), nullable=False),
        sa.Column("dst_adjusted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("utc_offset_seconds", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "(trigger_kind = 'scheduled' AND scheduled_for IS NOT NULL "
            "AND trigger_id IS NULL) OR "
            "(trigger_kind = 'manual' AND scheduled_for IS NULL "
            "AND trigger_id IS NOT NULL)",
            name=op.f("ck_schedule_occurrences_trigger_fields_consistent"),
        ),
        sa.CheckConstraint(
            "trigger_kind IN ('scheduled', 'manual')",
            name=op.f("ck_schedule_occurrences_trigger_kind"),
        ),
        sa.CheckConstraint(
            "status IN ('materialized', 'misfire_blocked')",
            name=op.f("ck_schedule_occurrences_status"),
        ),
        sa.CheckConstraint(
            "(status = 'materialized' AND job_id IS NOT NULL "
            "AND error_code IS NULL) OR "
            "(status = 'misfire_blocked' AND job_id IS NULL "
            "AND error_code IS NOT NULL)",
            name=op.f("ck_schedule_occurrences_materialization_state_consistent"),
        ),
        sa.CheckConstraint(
            "trigger_kind = 'manual' OR "
            "(window_start <= scheduled_for AND scheduled_for <= window_end)",
            name=op.f("ck_schedule_occurrences_window_contains_scheduled_time"),
        ),
        sa.CheckConstraint(
            "coalesced_count >= 1",
            name=op.f("ck_schedule_occurrences_coalesced_count_positive"),
        ),
        sa.CheckConstraint(
            "utc_offset_seconds > -86400 AND utc_offset_seconds < 86400",
            name=op.f("ck_schedule_occurrences_utc_offset_bounds"),
        ),
        sa.CheckConstraint(
            "schedule_version >= 1", name=op.f("ck_schedule_occurrences_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_schedule_occurrences_job_id_jobs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
            name=op.f("fk_schedule_occurrences_schedule_id_schedules"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_occurrences")),
        sa.UniqueConstraint("job_id", name=op.f("uq_schedule_occurrences_job_id")),
    )
    op.create_index(
        op.f("ix_schedule_occurrences_schedule_id_created_at"),
        "schedule_occurrences",
        ["schedule_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_schedule_occurrences_manual_trigger",
        "schedule_occurrences",
        ["trigger_id"],
        unique=True,
        postgresql_where=sa.text("trigger_kind = 'manual'"),
    )
    op.create_index(
        "uq_schedule_occurrences_scheduled",
        "schedule_occurrences",
        ["schedule_id", "scheduled_for"],
        unique=True,
        postgresql_where=sa.text("trigger_kind = 'scheduled'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_schedule_occurrences_scheduled",
        table_name="schedule_occurrences",
        postgresql_where=sa.text("trigger_kind = 'scheduled'"),
    )
    op.drop_index(
        "uq_schedule_occurrences_manual_trigger",
        table_name="schedule_occurrences",
        postgresql_where=sa.text("trigger_kind = 'manual'"),
    )
    op.drop_index(
        op.f("ix_schedule_occurrences_schedule_id_created_at"), table_name="schedule_occurrences"
    )
    op.drop_table("schedule_occurrences")
    op.drop_index(
        "uq_outbox_workspace_deduplication",
        table_name="outbox_events",
        postgresql_where=sa.text("workspace_id IS NOT NULL AND deduplication_key IS NOT NULL"),
    )
    op.drop_index(
        "uq_outbox_system_deduplication",
        table_name="outbox_events",
        postgresql_where=sa.text("system_scope_key IS NOT NULL AND deduplication_key IS NOT NULL"),
    )
    op.drop_index(
        "uq_outbox_job_dispatch_generation",
        table_name="outbox_events",
        postgresql_where=sa.text("source_job_id IS NOT NULL"),
    )
    op.drop_index(
        op.f("ix_outbox_events_status_next_attempt_at_created_at"), table_name="outbox_events"
    )
    op.drop_index(
        "ix_outbox_events_expired_claims",
        table_name="outbox_events",
        postgresql_where=sa.text("status = 'publishing'"),
    )
    op.drop_table("outbox_events")
    op.drop_index(
        "uq_job_events_one_terminal_per_job",
        table_name="job_events",
        postgresql_where=sa.text(
            "event_type IN ('succeeded', 'failed', 'cancelled', 'dead_letter')"
        ),
    )
    op.drop_index(op.f("ix_job_events_job_id_occurred_at"), table_name="job_events")
    op.drop_table("job_events")
    op.drop_index(
        "uq_schedules_workspace_name",
        table_name="schedules",
        postgresql_where=sa.text("workspace_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_schedules_system_name",
        table_name="schedules",
        postgresql_where=sa.text("system_scope_key IS NOT NULL"),
    )
    op.drop_index("ix_schedules_due", table_name="schedules", postgresql_where=sa.text("enabled"))
    op.drop_table("schedules")
    op.drop_index(
        "uq_jobs_workspace_idempotency",
        table_name="jobs",
        postgresql_where=sa.text("workspace_id IS NOT NULL AND idempotency_key_hash IS NOT NULL"),
    )
    op.drop_index(
        "uq_jobs_system_idempotency",
        table_name="jobs",
        postgresql_where=sa.text(
            "system_scope_key IS NOT NULL AND idempotency_key_hash IS NOT NULL"
        ),
    )
    op.drop_index(op.f("ix_jobs_status_available_at_priority_created_at"), table_name="jobs")
    op.drop_index(
        "ix_jobs_expired_leases", table_name="jobs", postgresql_where=sa.text("status = 'running'")
    )
    op.drop_table("jobs")
    # ### end Alembic commands ###
