"""create identity and workspace schema

Revision ID: 92864e62ffff
Revises:
Create Date: 2026-08-06 10:35:57.515446

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision: str = "92864e62ffff"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "disabled",
                "deleting",
                "deleted",
                name="user_status",
                native_enum=False,
                create_constraint=False,
                length=16,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "password_changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("email = lower(btrim(email))", name=op.f("ck_users_email_normalized")),
        sa.CheckConstraint(
            "status IN ('active', 'disabled', 'deleting', 'deleted')",
            name=op.f("ck_users_user_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "refresh_session_families",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("current_session_id", sa.Uuid(), nullable=True),
        sa.Column("absolute_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revocation_reason", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "absolute_expires_at > created_at",
            name=op.f("ck_refresh_session_families_absolute_expiration_after_creation"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_session_families_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_session_families")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_refresh_session_families_id_user_id")),
    )
    op.create_index(
        op.f("ix_refresh_session_families_user_id_revoked_at"),
        "refresh_session_families",
        ["user_id", "revoked_at"],
        unique=False,
    )
    op.create_table(
        "workspaces",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "deleting",
                "deleted",
                name="workspace_status",
                native_enum=False,
                create_constraint=False,
                length=16,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(btrim(name)) > 0", name=op.f("ck_workspaces_name_not_blank")),
        sa.CheckConstraint(
            "status IN ('active', 'deleting', 'deleted')",
            name=op.f("ck_workspaces_workspace_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_workspaces_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum(
                "succeeded",
                "denied",
                "failed",
                name="audit_outcome",
                native_enum=False,
                create_constraint=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column(
            "metadata_schema_version",
            sa.SmallInteger(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column(
            "sanitized_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "metadata_schema_version > 0",
            name=op.f("ck_audit_logs_metadata_schema_version_positive"),
        ),
        sa.CheckConstraint(
            "outcome IN ('succeeded', 'denied', 'failed')",
            name=op.f("ck_audit_logs_audit_outcome"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_audit_logs_workspace_id_workspaces"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        op.f("ix_audit_logs_actor_user_id_created_at"),
        "audit_logs",
        ["actor_user_id", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_audit_logs_trace_id"), "audit_logs", ["trace_id"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_workspace_id_created_at"),
        "audit_logs",
        ["workspace_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "refresh_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("rotation_family_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("csrf_token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("device_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("previous_session_id", sa.Uuid(), nullable=True),
        sa.Column("replaced_by_session_id", sa.Uuid(), nullable=True),
        sa.Column("idle_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("absolute_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revocation_reason", sa.String(length=64), nullable=True),
        sa.Column("recovery_envelope", sa.LargeBinary(), nullable=True),
        sa.Column("recovery_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(recovery_envelope IS NULL) = (recovery_expires_at IS NULL)",
            name=op.f("ck_refresh_sessions_recovery_fields_paired"),
        ),
        sa.CheckConstraint(
            "(used_at IS NULL AND replaced_by_session_id IS NULL) "
            "OR (used_at IS NOT NULL AND replaced_by_session_id IS NOT NULL)",
            name=op.f("ck_refresh_sessions_rotation_state_consistent"),
        ),
        sa.CheckConstraint(
            "idle_expires_at <= absolute_expires_at",
            name=op.f("ck_refresh_sessions_expiration_order"),
        ),
        sa.CheckConstraint(
            "octet_length(csrf_token_hash) = 32",
            name=op.f("ck_refresh_sessions_csrf_token_hash_length"),
        ),
        sa.CheckConstraint(
            "octet_length(device_hash) = 32", name=op.f("ck_refresh_sessions_device_hash_length")
        ),
        sa.CheckConstraint(
            "octet_length(token_hash) = 32", name=op.f("ck_refresh_sessions_token_hash_length")
        ),
        sa.CheckConstraint(
            "previous_session_id IS NULL OR previous_session_id <> id",
            name=op.f("ck_refresh_sessions_previous_session_not_self"),
        ),
        sa.CheckConstraint(
            "replaced_by_session_id IS NULL OR replaced_by_session_id <> id",
            name=op.f("ck_refresh_sessions_replacement_session_not_self"),
        ),
        sa.ForeignKeyConstraint(
            ["previous_session_id"],
            ["refresh_sessions.id"],
            name=op.f("fk_refresh_sessions_previous_session_id_refresh_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_session_id"],
            ["refresh_sessions.id"],
            name=op.f("fk_refresh_sessions_replaced_by_session_id_refresh_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["rotation_family_id", "user_id"],
            ["refresh_session_families.id", "refresh_session_families.user_id"],
            name="fk_refresh_sessions_family_user_refresh_session_families",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_sessions_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_sessions")),
        sa.UniqueConstraint("csrf_token_hash", name=op.f("uq_refresh_sessions_csrf_token_hash")),
        sa.UniqueConstraint(
            "previous_session_id", name=op.f("uq_refresh_sessions_previous_session_id")
        ),
        sa.UniqueConstraint(
            "replaced_by_session_id", name=op.f("uq_refresh_sessions_replaced_by_session_id")
        ),
        sa.UniqueConstraint(
            "rotation_family_id", "id", name=op.f("uq_refresh_sessions_rotation_family_id_id")
        ),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_sessions_token_hash")),
    )
    op.create_index(
        "ix_refresh_sessions_pending_recovery_expiry",
        "refresh_sessions",
        ["recovery_expires_at"],
        unique=False,
        postgresql_where=sa.text("recovery_expires_at IS NOT NULL"),
    )
    op.create_foreign_key(
        "fk_refresh_session_families_current_session_id_refresh_sessions",
        "refresh_session_families",
        "refresh_sessions",
        ["id", "current_session_id"],
        ["rotation_family_id", "id"],
        ondelete="RESTRICT",
    )
    op.create_index(
        op.f("ix_refresh_sessions_rotation_family_id_created_at"),
        "refresh_sessions",
        ["rotation_family_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_sessions_user_id_revoked_at"),
        "refresh_sessions",
        ["user_id", "revoked_at"],
        unique=False,
    )
    op.create_table(
        "workspace_members",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "admin",
                "member",
                "viewer",
                name="workspace_role",
                native_enum=False,
                create_constraint=False,
                length=16,
            ),
            server_default="member",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'member', 'viewer')",
            name=op.f("ck_workspace_members_workspace_role"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_workspace_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_workspace_members_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_members")),
        sa.UniqueConstraint(
            "workspace_id", "user_id", name=op.f("uq_workspace_members_workspace_id_user_id")
        ),
    )
    op.create_index(
        op.f("ix_workspace_members_user_id_workspace_id"),
        "workspace_members",
        ["user_id", "workspace_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workspace_members_workspace_id_role"),
        "workspace_members",
        ["workspace_id", "role"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workspace_members_workspace_id_role"), table_name="workspace_members")
    op.drop_index(op.f("ix_workspace_members_user_id_workspace_id"), table_name="workspace_members")
    op.drop_table("workspace_members")
    op.drop_index(op.f("ix_refresh_sessions_user_id_revoked_at"), table_name="refresh_sessions")
    op.drop_index(
        op.f("ix_refresh_sessions_rotation_family_id_created_at"), table_name="refresh_sessions"
    )
    op.drop_index(
        "ix_refresh_sessions_pending_recovery_expiry",
        table_name="refresh_sessions",
        postgresql_where=sa.text("recovery_expires_at IS NOT NULL"),
    )
    op.drop_constraint(
        "fk_refresh_session_families_current_session_id_refresh_sessions",
        "refresh_session_families",
        type_="foreignkey",
    )
    op.drop_table("refresh_sessions")
    op.drop_index(op.f("ix_audit_logs_workspace_id_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_trace_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_user_id_created_at"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("workspaces")
    op.drop_index(
        op.f("ix_refresh_session_families_user_id_revoked_at"),
        table_name="refresh_session_families",
    )
    op.drop_table("refresh_session_families")
    op.drop_table("users")
    # ### end Alembic commands ###
