"""create conversation and agent runtime facts

Revision ID: ea2832a756ce
Revises: 198d18b12698
Create Date: 2026-08-13 21:20:00.701108

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision: str = "ea2832a756ce"
down_revision: str | Sequence[str] | None = "198d18b12698"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "deleted", name="conversation_status", native_enum=False, length=16),
            server_default="active",
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'deleted' AND deleted_at IS NOT NULL) OR "
            "(status = 'active' AND deleted_at IS NULL)",
            name=op.f("ck_conversations_deletion_state_consistent"),
        ),
        sa.CheckConstraint("status IN ('active', 'deleted')", name=op.f("ck_conversations_status")),
        sa.CheckConstraint(
            "length(btrim(title)) > 0", name=op.f("ck_conversations_title_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_conversations_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_conversations_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint("id", "workspace_id", name=op.f("uq_conversations_id_workspace_id")),
    )
    op.create_index(
        op.f("ix_conversations_workspace_id_updated_at_id"),
        "conversations",
        ["workspace_id", "updated_at", "id"],
        unique=False,
    )
    op.create_table(
        "conversation_turns",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "search_mode",
            sa.Enum(
                "none",
                "web",
                "local",
                "both",
                name="turn_search_mode",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("industry_id", sa.Uuid(), nullable=True),
        sa.Column(
            "knowledge_base_ids",
            postgresql.ARRAY(sa.Uuid()),
            server_default=sa.text("'{}'::uuid[]"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "search_mode <> 'none' OR cardinality(knowledge_base_ids) = 0",
            name=op.f("ck_conversation_turns_none_mode_has_no_knowledge_bases"),
        ),
        sa.CheckConstraint(
            "search_mode IN ('none', 'web', 'local', 'both')",
            name=op.f("ck_conversation_turns_search_mode"),
        ),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_conversation_turns_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["conversation_id", "workspace_id"],
            ["conversations.id", "conversations.workspace_id"],
            name=op.f("fk_conversation_turns_conversation_id_workspace_id_conversations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_conversation_turns_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversation_turns")),
        sa.UniqueConstraint(
            "conversation_id",
            "sequence",
            name=op.f("uq_conversation_turns_conversation_id_sequence"),
        ),
        sa.UniqueConstraint(
            "id", "workspace_id", name=op.f("uq_conversation_turns_id_workspace_id")
        ),
    )
    op.create_index(
        op.f("ix_conversation_turns_workspace_id_conversation_id_sequence"),
        "conversation_turns",
        ["workspace_id", "conversation_id", "sequence"],
        unique=False,
    )
    op.create_table(
        "agent_runs",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("turn_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("event_stream_id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.String(length=128), nullable=False),
        sa.Column(
            "run_type",
            sa.Enum(
                "direct_answer",
                "tool_loop",
                "research",
                name="agent_run_type",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "paused",
                "completed",
                "failed",
                "cancelled",
                name="agent_run_status",
                native_enum=False,
                length=16,
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column(
            "stop_reason",
            sa.Enum(
                "final",
                "cancelled",
                "provider_timeout",
                "provider_rate_limited",
                "provider_error",
                "invalid_provider_response",
                "incomplete_provider_response",
                "max_steps",
                "deadline_exceeded",
                "token_budget_exceeded",
                "cost_budget_exceeded",
                "tool_denied",
                "tool_error",
                "no_progress",
                "approval_required",
                "runtime_error",
                name="run_stop_reason",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("runtime_version", sa.String(length=128), nullable=False),
        sa.Column("harness_version", sa.String(length=128), nullable=False),
        sa.Column("state_revision", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.SmallInteger(), nullable=False),
        sa.Column("max_steps", sa.Integer(), nullable=False),
        sa.Column("max_total_tokens", sa.Integer(), nullable=False),
        sa.Column("max_cost_micro_usd", sa.BigInteger(), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_count", sa.Integer(), nullable=False),
        sa.Column("step_count", sa.Integer(), nullable=False),
        sa.Column("input_tokens_used", sa.Integer(), nullable=False),
        sa.Column("output_tokens_used", sa.Integer(), nullable=False),
        sa.Column("cached_input_tokens_used", sa.Integer(), nullable=False),
        sa.Column("cost_micro_usd", sa.BigInteger(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terminal_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status IN ('completed', 'failed', 'cancelled') "
            "AND terminal_at IS NOT NULL AND stop_reason IS NOT NULL) OR "
            "(status NOT IN ('completed', 'failed', 'cancelled') "
            "AND terminal_at IS NULL AND stop_reason IS NULL)",
            name=op.f("ck_agent_runs_terminal_state_consistent"),
        ),
        sa.CheckConstraint(
            "run_type IN ('direct_answer', 'tool_loop', 'research')",
            name=op.f("ck_agent_runs_run_type"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'paused', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_agent_runs_status"),
        ),
        sa.CheckConstraint(
            "deadline > created_at", name=op.f("ck_agent_runs_deadline_after_creation")
        ),
        sa.CheckConstraint("event_count >= 1", name=op.f("ck_agent_runs_event_count_positive")),
        sa.CheckConstraint(
            "input_tokens_used >= 0 AND output_tokens_used >= 0 "
            "AND cached_input_tokens_used >= 0 AND cost_micro_usd >= 0",
            name=op.f("ck_agent_runs_usage_nonnegative"),
        ),
        sa.CheckConstraint(
            "state_revision >= 0", name=op.f("ck_agent_runs_state_revision_nonnegative")
        ),
        sa.CheckConstraint("step_count >= 0", name=op.f("ck_agent_runs_step_count_nonnegative")),
        sa.ForeignKeyConstraint(
            ["conversation_id", "workspace_id"],
            ["conversations.id", "conversations.workspace_id"],
            name=op.f("fk_agent_runs_conversation_id_workspace_id_conversations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_agent_runs_job_id_jobs"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["turn_id", "workspace_id"],
            ["conversation_turns.id", "conversation_turns.workspace_id"],
            name=op.f("fk_agent_runs_turn_id_workspace_id_conversation_turns"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_agent_runs_user_id_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_agent_runs_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
        sa.UniqueConstraint("event_stream_id", name=op.f("uq_agent_runs_event_stream_id")),
        sa.UniqueConstraint("id", "workspace_id", name=op.f("uq_agent_runs_id_workspace_id")),
        sa.UniqueConstraint("job_id", name=op.f("uq_agent_runs_job_id")),
    )
    op.create_index(
        op.f("ix_agent_runs_workspace_id_conversation_id_created_at_id"),
        "agent_runs",
        ["workspace_id", "conversation_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_runs_workspace_id_status_updated_at"),
        "agent_runs",
        ["workspace_id", "status", "updated_at"],
        unique=False,
    )
    op.create_table(
        "agent_checkpoints",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("envelope_schema_version", sa.SmallInteger(), nullable=False),
        sa.Column("state_schema_version", sa.SmallInteger(), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("saved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "envelope_schema_version >= 1 AND state_schema_version >= 1",
            name=op.f("ck_agent_checkpoints_schema_versions_positive"),
        ),
        sa.CheckConstraint("revision >= 0", name=op.f("ck_agent_checkpoints_revision_nonnegative")),
        sa.ForeignKeyConstraint(
            ["run_id", "workspace_id"],
            ["agent_runs.id", "agent_runs.workspace_id"],
            name=op.f("fk_agent_checkpoints_run_id_workspace_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_checkpoints")),
        sa.UniqueConstraint(
            "run_id", "revision", name=op.f("uq_agent_checkpoints_run_id_revision")
        ),
    )
    op.create_index(
        op.f("ix_agent_checkpoints_workspace_id_run_id_revision"),
        "agent_checkpoints",
        ["workspace_id", "run_id", "revision"],
        unique=False,
    )
    op.create_table(
        "agent_events",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("stream_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trace_id", sa.String(length=128), nullable=False),
        sa.Column("schema_version", sa.SmallInteger(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "agent.run.queued",
                "agent.run.started",
                "agent.run.paused",
                "agent.run.resumed",
                "agent.run.completed",
                "agent.run.failed",
                "agent.run.cancelled",
                "agent.step.started",
                "agent.step.completed",
                "agent.step.failed",
                "agent.model.started",
                "agent.model.delta",
                "agent.model.completed",
                "agent.artifact.created",
                "agent.checkpoint.saved",
                name="agent_event_type",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_agent_events_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["run_id", "workspace_id"],
            ["agent_runs.id", "agent_runs.workspace_id"],
            name=op.f("fk_agent_events_run_id_workspace_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_events")),
        sa.UniqueConstraint(
            "stream_id", "sequence", name=op.f("uq_agent_events_stream_id_sequence")
        ),
    )
    op.create_index(
        op.f("ix_agent_events_workspace_id_run_id_sequence"),
        "agent_events",
        ["workspace_id", "run_id", "sequence"],
        unique=False,
    )
    op.create_index(
        "uq_agent_events_one_terminal_per_run",
        "agent_events",
        ["run_id"],
        unique=True,
        postgresql_where=sa.text(
            "event_type IN ('agent.run.completed', 'agent.run.failed', 'agent.run.cancelled')"
        ),
    )
    op.create_table(
        "agent_steps",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "model",
                "tool",
                "approval",
                "checkpoint",
                "final",
                name="agent_step_kind",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "completed",
                "failed",
                "cancelled",
                name="agent_step_status",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("last_event_sequence", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_micro_usd", sa.BigInteger(), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "(status = 'running' AND completed_at IS NULL) OR "
            "(status <> 'running' AND completed_at IS NOT NULL)",
            name=op.f("ck_agent_steps_completion_state_consistent"),
        ),
        sa.CheckConstraint(
            "kind IN ('model', 'tool', 'approval', 'checkpoint', 'final')",
            name=op.f("ck_agent_steps_kind"),
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_agent_steps_status"),
        ),
        sa.CheckConstraint(
            "input_tokens >= 0 AND output_tokens >= 0 AND cost_micro_usd >= 0",
            name=op.f("ck_agent_steps_usage_nonnegative"),
        ),
        sa.CheckConstraint(
            "last_event_sequence >= 1", name=op.f("ck_agent_steps_last_event_sequence_positive")
        ),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_agent_steps_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["run_id", "workspace_id"],
            ["agent_runs.id", "agent_runs.workspace_id"],
            name=op.f("fk_agent_steps_run_id_workspace_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_steps")),
        sa.UniqueConstraint(
            "id", "run_id", "workspace_id", name=op.f("uq_agent_steps_id_run_id_workspace_id")
        ),
        sa.UniqueConstraint("run_id", "sequence", name=op.f("uq_agent_steps_run_id_sequence")),
    )
    op.create_index(
        op.f("ix_agent_steps_workspace_id_run_id_sequence"),
        "agent_steps",
        ["workspace_id", "run_id", "sequence"],
        unique=False,
    )
    op.create_table(
        "conversation_messages",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("turn_id", sa.Uuid(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("user", "assistant", name="message_role", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "committed", "partial", "final", name="message_status", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("content_markdown", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(role = 'user' AND status = 'committed' "
            "AND created_by_user_id IS NOT NULL) OR "
            "(role = 'assistant' AND status IN ('partial', 'final') "
            "AND created_by_user_id IS NULL)",
            name=op.f("ck_conversation_messages_role_state_consistent"),
        ),
        sa.CheckConstraint(
            "role IN ('user', 'assistant')", name=op.f("ck_conversation_messages_role")
        ),
        sa.CheckConstraint(
            "status IN ('committed', 'partial', 'final')",
            name=op.f("ck_conversation_messages_status"),
        ),
        sa.CheckConstraint(
            "length(btrim(content_markdown)) > 0",
            name=op.f("ck_conversation_messages_content_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id", "workspace_id"],
            ["agent_runs.id", "agent_runs.workspace_id"],
            name=op.f("fk_conversation_messages_agent_run_id_workspace_id_agent_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_conversation_messages_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["turn_id", "workspace_id"],
            ["conversation_turns.id", "conversation_turns.workspace_id"],
            name=op.f("fk_conversation_messages_turn_id_workspace_id_conversation_turns"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversation_messages")),
    )
    op.create_index(
        op.f("ix_conversation_messages_workspace_id_turn_id_created_at_id"),
        "conversation_messages",
        ["workspace_id", "turn_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "uq_conversation_messages_one_final_per_run",
        "conversation_messages",
        ["agent_run_id"],
        unique=True,
        postgresql_where=sa.text("role = 'assistant' AND status = 'final'"),
    )
    op.create_index(
        "uq_conversation_messages_one_user_input_per_turn",
        "conversation_messages",
        ["turn_id"],
        unique=True,
        postgresql_where=sa.text("role = 'user'"),
    )
    op.create_table(
        "context_manifests",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=False),
        sa.Column("schema_version", sa.SmallInteger(), nullable=False),
        sa.Column("compiler_version", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=128), nullable=False),
        sa.Column("runtime_projection_version", sa.String(length=128), nullable=False),
        sa.Column("token_counter_version", sa.String(length=128), nullable=False),
        sa.Column("budget", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["step_id", "run_id", "workspace_id"],
            ["agent_steps.id", "agent_steps.run_id", "agent_steps.workspace_id"],
            name=op.f("fk_context_manifests_step_id_run_id_workspace_id_agent_steps"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_context_manifests")),
        sa.UniqueConstraint("step_id", name=op.f("uq_context_manifests_step_id")),
    )
    op.create_index(
        op.f("ix_context_manifests_workspace_id_run_id_created_at"),
        "context_manifests",
        ["workspace_id", "run_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "run_artifacts",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("originating_step_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "report",
                "table",
                "chart",
                "file",
                "evidence_set",
                name="run_artifact_kind",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("resource_ref", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(resource_ref)) > 0", name=op.f("ck_run_artifacts_resource_ref_not_blank")
        ),
        sa.CheckConstraint(
            "length(content_sha256) = 64", name=op.f("ck_run_artifacts_content_hash_length")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_run_artifacts_version_positive")),
        sa.ForeignKeyConstraint(
            ["originating_step_id", "run_id", "workspace_id"],
            ["agent_steps.id", "agent_steps.run_id", "agent_steps.workspace_id"],
            name=op.f("fk_run_artifacts_originating_step_id_run_id_workspace_id_agent_steps"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "workspace_id"],
            ["agent_runs.id", "agent_runs.workspace_id"],
            name=op.f("fk_run_artifacts_run_id_workspace_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_artifacts")),
    )
    op.create_index(
        op.f("ix_run_artifacts_workspace_id_run_id_created_at"),
        "run_artifacts",
        ["workspace_id", "run_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_run_artifacts_workspace_id_run_id_created_at"), table_name="run_artifacts"
    )
    op.drop_table("run_artifacts")
    op.drop_index(
        op.f("ix_context_manifests_workspace_id_run_id_created_at"), table_name="context_manifests"
    )
    op.drop_table("context_manifests")
    op.drop_index(
        "uq_conversation_messages_one_user_input_per_turn",
        table_name="conversation_messages",
        postgresql_where=sa.text("role = 'user'"),
    )
    op.drop_index(
        "uq_conversation_messages_one_final_per_run",
        table_name="conversation_messages",
        postgresql_where=sa.text("role = 'assistant' AND status = 'final'"),
    )
    op.drop_index(
        op.f("ix_conversation_messages_workspace_id_turn_id_created_at_id"),
        table_name="conversation_messages",
    )
    op.drop_table("conversation_messages")
    op.drop_index(op.f("ix_agent_steps_workspace_id_run_id_sequence"), table_name="agent_steps")
    op.drop_table("agent_steps")
    op.drop_index(
        "uq_agent_events_one_terminal_per_run",
        table_name="agent_events",
        postgresql_where=sa.text(
            "event_type IN ('agent.run.completed', 'agent.run.failed', 'agent.run.cancelled')"
        ),
    )
    op.drop_index(op.f("ix_agent_events_workspace_id_run_id_sequence"), table_name="agent_events")
    op.drop_table("agent_events")
    op.drop_index(
        op.f("ix_agent_checkpoints_workspace_id_run_id_revision"), table_name="agent_checkpoints"
    )
    op.drop_table("agent_checkpoints")
    op.drop_index(op.f("ix_agent_runs_workspace_id_status_updated_at"), table_name="agent_runs")
    op.drop_index(
        op.f("ix_agent_runs_workspace_id_conversation_id_created_at_id"), table_name="agent_runs"
    )
    op.drop_table("agent_runs")
    op.drop_index(
        op.f("ix_conversation_turns_workspace_id_conversation_id_sequence"),
        table_name="conversation_turns",
    )
    op.drop_table("conversation_turns")
    op.drop_index(op.f("ix_conversations_workspace_id_updated_at_id"), table_name="conversations")
    op.drop_table("conversations")
    # ### end Alembic commands ###
