"""Private file lifecycle and bounded attachment parsing."""

from industry_platform.modules.files.domain import (
    ATTACHMENT_PARSER_VERSION,
    ATTACHMENT_SANITIZER_VERSION,
    DEFAULT_ATTACHMENT_LIMITS,
    FILE_CONTRACT_SCHEMA_VERSION,
    MAX_ATTACHMENT_BYTES,
    MAX_DISPLAY_FILENAME_CHARACTERS,
    MAX_IMAGE_ATTACHMENT_BYTES,
    MAX_IMAGE_HEIGHT,
    MAX_IMAGE_PIXELS,
    MAX_IMAGE_WIDTH,
    MAX_RAW_FILENAME_CHARACTERS,
    MAX_TEXT_ATTACHMENT_BYTES,
    MAX_TEXT_ATTACHMENT_CHARACTERS,
    AttachmentKind,
    AttachmentLimits,
    AttachmentMediaType,
    AttachmentParserPort,
    AttachmentValidationCode,
    AttachmentValidationError,
    FileObjectPurpose,
    FileObjectStatus,
    ParseAttachmentRequest,
    ParsedAttachment,
    ParsedImageMetadata,
    normalize_media_type,
    require_matching_extension,
    sanitize_display_filename,
)
from industry_platform.modules.files.parser import BoundedAttachmentParser, parse_attachment

__all__ = [
    "ATTACHMENT_PARSER_VERSION",
    "ATTACHMENT_SANITIZER_VERSION",
    "DEFAULT_ATTACHMENT_LIMITS",
    "FILE_CONTRACT_SCHEMA_VERSION",
    "MAX_ATTACHMENT_BYTES",
    "MAX_DISPLAY_FILENAME_CHARACTERS",
    "MAX_IMAGE_ATTACHMENT_BYTES",
    "MAX_IMAGE_HEIGHT",
    "MAX_IMAGE_PIXELS",
    "MAX_IMAGE_WIDTH",
    "MAX_RAW_FILENAME_CHARACTERS",
    "MAX_TEXT_ATTACHMENT_BYTES",
    "MAX_TEXT_ATTACHMENT_CHARACTERS",
    "AttachmentKind",
    "AttachmentLimits",
    "AttachmentMediaType",
    "AttachmentParserPort",
    "AttachmentValidationCode",
    "AttachmentValidationError",
    "BoundedAttachmentParser",
    "FileObjectPurpose",
    "FileObjectStatus",
    "ParseAttachmentRequest",
    "ParsedAttachment",
    "ParsedImageMetadata",
    "normalize_media_type",
    "parse_attachment",
    "require_matching_extension",
    "sanitize_display_filename",
]
